version: '3.8'
services:
  r-rocketchat:
    image: rocket.chat
    restart: always
    volumes:
      - ./data/uploads:/app/uploads
    environment:
      - ROOT_URL=http://r.localhost
      - MONGO_URL=mongodb://r-mongo:27017/local
      - MONGO_OPLOG_URL=mongodb://r-mongo:27017/local
    networks:
      - docker_default
      - default
  r-mongo:
    image: mongo:4.0
    restart: always
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
    labels:
      - "traefik.enable=false"
  r-init:
    image: mongo:4.0
    command: 'mongo r-mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'

networks:
  docker_default:
    external: true
    name: docker_default
      